package de.shellfire.vpn.android;

import org.jetbrains.annotations.NotNull;

/**
 * @author bettmenn
 */
public enum Country {
    Afghanistan("Afghanistan", Continent.ASIA),
    Egypt("Egypt", Continent.AFRICA),
    Albania("Albania", Continent.EUROPE),
    Algeria("Algeria", Continent.AFRICA),
    AmericanSamoa("American Samoa", Continent.OCEANIA),
    UnitedStatesMinorOutlyingIslands("United States Minor Outlying Islands", Continent.NORTH_AMERICA),
    Andorra("Andorra", Continent.EUROPE),
    Angola("Angola", Continent.AFRICA),
    Anguilla("Anguilla", Continent.NORTH_AMERICA),
    Antarctica("Antarctica", Continent.ANTARCTICA),
    AntiguaandBarbuda("Antigua and Barbuda", Continent.NORTH_AMERICA),
    EquatorialGuinea("Equatorial Guinea", Continent.AFRICA),
    Argentina("Argentina", Continent.SOUTH_AMERICA),
    Armenia("Armenia", Continent.ASIA),
    Aruba("Aruba", Continent.NORTH_AMERICA),
    Azerbaijan("Azerbaijan", Continent.ASIA),
    Ethiopia("Ethiopia", Continent.AFRICA),
    Australia("Australia", Continent.OCEANIA),
    Bahamas("Bahamas", Continent.NORTH_AMERICA),
    Bahrain("Bahrain", Continent.ASIA),
    Bangladesh("Bangladesh", Continent.ASIA),
    Barbados("Barbados", Continent.NORTH_AMERICA),
    Belarus("Belarus", Continent.EUROPE),
    Belgium("Belgium", Continent.EUROPE),
    Belize("Belize", Continent.NORTH_AMERICA),
    Benin("Benin", Continent.AFRICA),
    Bermuda("Bermuda", Continent.NORTH_AMERICA),
    Bhutan("Bhutan", Continent.ASIA),
    Bolivia("Bolivia", Continent.SOUTH_AMERICA),
    BosniaandHerzegovina("Bosnia and Herzegovina", Continent.EUROPE),
    Botswana("Botswana", Continent.AFRICA),
    BouvetIsland("Bouvet Island", Continent.ANTARCTICA),
    Brazil("Brazil", Continent.SOUTH_AMERICA),
    BritishIndianOceanTerritory("British Indian Ocean Territory", Continent.ASIA),
    BruneiDarussalam("Brunei Darussalam", Continent.ASIA),
    Bulgaria("Bulgaria", Continent.EUROPE),
    BurkinaFaso("Burkina Faso", Continent.AFRICA),
    Burundi("Burundi", Continent.AFRICA),
    Chile("Chile", Continent.SOUTH_AMERICA),
    China("China", Continent.ASIA),
    CookIslands("Cook Islands", Continent.OCEANIA),
    CostaRica("Costa Rica", Continent.NORTH_AMERICA),
    CotedIvoire("Cote d'Ivoire", Continent.AFRICA),
    Denmark("Denmark", Continent.EUROPE),
    Germany("Germany", Continent.EUROPE),
    Dominica("Dominica", Continent.NORTH_AMERICA),
    DominicanRepublic("Dominican Republic", Continent.NORTH_AMERICA),
    Djibouti("Djibouti", Continent.AFRICA),
    Ecuador("Ecuador", Continent.SOUTH_AMERICA),
    ElSalvador("El Salvador", Continent.NORTH_AMERICA),
    Eritrea("Eritrea", Continent.AFRICA),
    Estonia("Estonia", Continent.EUROPE),
    FalklandIslands("Falkland Islands", Continent.SOUTH_AMERICA),
    FaroeIslands("Faroe Islands", Continent.EUROPE),
    Fiji("Fiji", Continent.OCEANIA),
    Finland("Finland", Continent.EUROPE),
    France("France", Continent.EUROPE),
    FrenchSouthernTerritories("French Southern Territories", Continent.ANTARCTICA),
    FrenchGuiana("French Guiana", Continent.SOUTH_AMERICA),
    FrenchPolynesia("French Polynesia", Continent.OCEANIA),
    Gabon("Gabon", Continent.AFRICA),
    Gambia("Gambia", Continent.AFRICA),
    Georgia("Georgia", Continent.ASIA),
    Ghana("Ghana", Continent.AFRICA),
    Gibraltar("Gibraltar", Continent.EUROPE),
    Grenada("Grenada", Continent.NORTH_AMERICA),
    Greece("Greece", Continent.EUROPE),
    Greenland("Greenland", Continent.NORTH_AMERICA),
    Guadeloupe("Guadeloupe", Continent.NORTH_AMERICA),
    Guam("Guam", Continent.OCEANIA),
    Guatemala("Guatemala", Continent.NORTH_AMERICA),
    Guinea("Guinea", Continent.AFRICA),
    GuineaBissau("Guinea-Bissau", Continent.AFRICA),
    Guyana("Guyana", Continent.SOUTH_AMERICA),
    Haiti("Haiti", Continent.NORTH_AMERICA),
    VaticanCityStateHolySee("Vatican City State (Holy See)", Continent.EUROPE),
    HeardIslandandMcDonaldIslands("Heard Island and McDonald Islands", Continent.ANTARCTICA),
    Honduras("Honduras", Continent.NORTH_AMERICA),
    HongKong("Hong Kong", Continent.ASIA),
    India("India", Continent.ASIA),
    Indonesia("Indonesia", Continent.ASIA),
    Iraq("Iraq", Continent.ASIA),
    Iran("Iran", Continent.ASIA),
    Ireland("Ireland", Continent.EUROPE),
    Iceland("Iceland", Continent.EUROPE),
    Israel("Israel", Continent.ASIA),
    IsleofMan("Isle of Man", Continent.EUROPE),
    Italy("Italy", Continent.EUROPE),
    Jamaica("Jamaica", Continent.NORTH_AMERICA),
    Japan("Japan", Continent.ASIA),
    Yemen("Yemen", Continent.ASIA),
    Jordan("Jordan", Continent.ASIA),
    Yugoslaviaformer("Yugoslavia (former)", Continent.EUROPE),
    CaymanIslands("Cayman Islands", Continent.NORTH_AMERICA),
    Cambodia("Cambodia", Continent.ASIA),
    Cameroon("Cameroon", Continent.AFRICA),
    Canada("Canada", Continent.NORTH_AMERICA),
    CapeVerde("Cape Verde", Continent.AFRICA),
    Kazakhstan("Kazakhstan", Continent.ASIA),
    Qatar("Qatar", Continent.ASIA),
    Kenya("Kenya", Continent.AFRICA),
    Kyrgyzstan("Kyrgyzstan", Continent.ASIA),
    Kiribati("Kiribati", Continent.OCEANIA),
    CocosIslands("Cocos Islands", Continent.OCEANIA),
    Colombia("Colombia", Continent.SOUTH_AMERICA),
    Comoros("Comoros", Continent.AFRICA),
    Congo("Congo", Continent.AFRICA),
    CongodemocraticRep("Congo (Democratic Rep)", Continent.AFRICA),
    KoreaDemocraticPeoplesRepublicof("Korea (Democratic People's Republic)", Continent.ASIA),
    KoreaRepublicof("Korea (Republic of)", Continent.ASIA),
    Croatia("Croatia", Continent.EUROPE),
    Cuba("Cuba", Continent.NORTH_AMERICA),
    Kuwait("Kuwait", Continent.ASIA),
    LatinAmerica("Latin America", Continent.SOUTH_AMERICA),
    Latvia("Latvia", Continent.EUROPE),
    Lebanon("Lebanon", Continent.ASIA),
    Liberia("Liberia", Continent.AFRICA),
    LibyanArabJamahiriya("Libyan Arab Jamahiriya", Continent.AFRICA),
    Liechtenstein("Liechtenstein", Continent.EUROPE),
    Lithuania("Lithuania", Continent.EUROPE),
    Luxembourg("Luxembourg", Continent.EUROPE),
    Macau("Macau", Continent.ASIA),
    Madagascar("Madagascar", Continent.AFRICA),
    Malawi("Malawi", Continent.AFRICA),
    Malaysia("Malaysia", Continent.ASIA),
    Maldives("Maldives", Continent.ASIA),
    Mali("Mali", Continent.AFRICA),
    Malta("Malta", Continent.EUROPE),
    MarianaIslands("Mariana Islands", Continent.OCEANIA),
    Morocco("Morocco", Continent.AFRICA),
    MarshallIslands("Marshall Islands", Continent.OCEANIA),
    Martinique("Martinique", Continent.NORTH_AMERICA),
    Mauritania("Mauritania", Continent.AFRICA),
    Mauritius("Mauritius", Continent.AFRICA),
    Mayotte("Mayotte", Continent.AFRICA),
    Macedonia("Macedonia", Continent.EUROPE),
    Mexico("Mexico", Continent.NORTH_AMERICA),
    MicronesiaFederatedStatesof("Micronesia (Federated States of)", Continent.OCEANIA),
    MoldovaRepublicof("Moldova", Continent.EUROPE),
    Mongolia("Mongolia", Continent.ASIA),
    Montserrat("Montserrat", Continent.NORTH_AMERICA),
    Mozambique("Mozambique", Continent.AFRICA),
    MyanmarBurma("Myanmar (Burma)", Continent.ASIA),
    Namibia("Namibia", Continent.AFRICA),
    Nauru("Nauru", Continent.OCEANIA),
    Nepal("Nepal", Continent.ASIA),
    NewCaledonia("New Caledonia", Continent.OCEANIA),
    NewZealand("New Zealand", Continent.OCEANIA),
    Nicaragua("Nicaragua", Continent.NORTH_AMERICA),
    Netherlands("Netherlands", Continent.EUROPE),
    NetherlandsAntilles("Netherlands Antilles", Continent.NORTH_AMERICA),
    Niger("Niger", Continent.AFRICA),
    Nigeria("Nigeria", Continent.AFRICA),
    Niue("Niue", Continent.OCEANIA),
    NorfolkIsland("Norfolk Island", Continent.OCEANIA),
    Norway("Norway", Continent.EUROPE),
    Oman("Oman", Continent.ASIA),
    Austria("Austria", Continent.EUROPE),
    EastTimor("East Timor", Continent.ASIA),
    Pakistan("Pakistan", Continent.ASIA),
    Palau("Palau", Continent.OCEANIA),
    Panama("Panama", Continent.NORTH_AMERICA),
    PapuaNewGuinea("Papua New Guinea", Continent.OCEANIA),
    Paraguay("Paraguay", Continent.SOUTH_AMERICA),
    Peru("Peru", Continent.SOUTH_AMERICA),
    Philippines("Philippines", Continent.ASIA),
    PitcairnIsland("Pitcairn Island", Continent.OCEANIA),
    Poland("Poland", Continent.EUROPE),
    Portugal("Portugal", Continent.EUROPE),
    PuertoRico("Puerto Rico", Continent.NORTH_AMERICA),
    Runion("Réunion", Continent.AFRICA),
    Rwanda("Rwanda", Continent.AFRICA),
    Romania("Romania", Continent.EUROPE),
    RussianFederation("Russian Federation", Continent.EUROPE),
    SolomonIslands("Solomon Islands", Continent.OCEANIA),
    Zambia("Zambia", Continent.AFRICA),
    Samoa("Samoa", Continent.OCEANIA),
    SanMarino("San Marino", Continent.EUROPE),
    SaoTomeandPrincipe("Sao Tome and Principe", Continent.AFRICA),
    SaudiArabia("Saudi Arabia", Continent.ASIA),
    Sweden("Sweden", Continent.EUROPE),
    Switzerland("Switzerland", Continent.EUROPE),
    Senegal("Senegal", Continent.AFRICA),
    Seychelles("Seychelles", Continent.AFRICA),
    SierraLeone("Sierra Leone", Continent.AFRICA),
    Zimbabwe("Zimbabwe", Continent.AFRICA),
    Singapore("Singapore", Continent.ASIA),
    Slovakia("Slovakia", Continent.EUROPE),
    Slovenia("Slovenia", Continent.EUROPE),
    Somalia("Somalia", Continent.AFRICA),
    Spain("Spain", Continent.EUROPE),
    SriLanka("Sri Lanka", Continent.ASIA),
    SaintHelena("Saint Helena", Continent.AFRICA),
    SaintKittsandNevis("Saint Kitts and Nevis", Continent.NORTH_AMERICA),
    SaintLucia("Saint Lucia", Continent.NORTH_AMERICA),
    SaintPierreandMiquelon("Saint Pierre and Miquelon", Continent.NORTH_AMERICA),
    SaintVincentandtheGrenadines("Saint Vincent and the Grenadines", Continent.NORTH_AMERICA),
    SouthAfrica("South Africa", Continent.AFRICA),
    Sudan("Sudan", Continent.AFRICA),
    SouthGeorgiaandthesouthSandwichIslands("South Georgia and the South Sandwich Islands", Continent.ANTARCTICA),
    Suriname("Suriname", Continent.SOUTH_AMERICA),
    SvalbardandJanMayen("Svalbard and Jan Mayen", Continent.EUROPE),
    Swaziland("Swaziland", Continent.AFRICA),
    SyrianArabRepublic("Syrian Arab Republic", Continent.ASIA),
    Tajikistan("Tajikistan", Continent.ASIA),
    TaiwanProvinceofChina("Taiwan Province of China", Continent.ASIA),
    TanzaniaUnitedRepublicof("Tanzania United Republic", Continent.AFRICA),
    Thailand("Thailand", Continent.ASIA),
    Togo("Togo", Continent.AFRICA),
    TokelauIslands("Tokelau Islands", Continent.OCEANIA),
    Tonga("Tonga", Continent.OCEANIA),
    TrinidadandTobago("Trinidad and Tobago", Continent.NORTH_AMERICA),
    Chad("Chad", Continent.AFRICA),
    CzechRepublic("Czech Republic", Continent.EUROPE),
    Tunisia("Tunisia", Continent.AFRICA),
    Turkey("Turkey", Continent.ASIA),
    Turkmenistan("Turkmenistan", Continent.ASIA),
    TurksandCaicosIslands("Turks and Caicos Islands", Continent.NORTH_AMERICA),
    Tuvalu("Tuvalu", Continent.OCEANIA),
    Uganda("Uganda", Continent.AFRICA),
    Ukraine("Ukraine", Continent.EUROPE),
    Hungary("Hungary", Continent.EUROPE),
    Uruguay("Uruguay", Continent.SOUTH_AMERICA),
    Uzbekistan("Uzbekistan", Continent.ASIA),
    Vanuatu("Vanuatu", Continent.OCEANIA),
    Venezuela("Venezuela", Continent.SOUTH_AMERICA),
    UnitedArabEmirates("United Arab Emirates", Continent.ASIA),
    UnitedStates("Usa", Continent.NORTH_AMERICA),
    UnitedKingdom("United Kingdom", Continent.EUROPE),
    Vietnam("Vietnam", Continent.ASIA),
    WallisandFutunaIslands("Wallis and Futuna Islands", Continent.OCEANIA),
    ChristmasIsland("Christmas Island", Continent.OCEANIA),
    CentralAfricanRepublic("Central African Republic", Continent.AFRICA),
    CentralAmerica("Central America", Continent.NORTH_AMERICA),
    Cyprus("Cyprus", Continent.ASIA),
    Serbia("Serbia", Continent.EUROPE);

    private String name;
    private Continent continent;

    Country(String name, Continent continent) {
        this.name = name;
        this.continent = continent;
    }

    Country(String name) {
        this.name = name;
    }

    Country() {
    }

    public static Country getByName(String name) {
        for (Country prop : values()) {
            if (prop.getName() != null && prop.getName().equals(name)) {
                return prop;
            }
        }

        throw new IllegalArgumentException(name + " is not a valid PropName");
    }

    @NotNull
    @Override
    public String toString() {
        return name;
    }

    public String getName() {
        return name;
    }

    public Continent getContinent() {
        return continent;
    }
}
